### ISSUE TITLE
Problem with thumbnail image

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1068] opened 2024-04-15 14:00 UTC
Hello @sahalali, I received the following email from Acolyte:

### **Original French Version**

De : Delisle-Rivest, Maxime-Julien <[maximejulien@acolyte.ws](mailto:maximejulien@acolyte.ws)>
Envoyé : 15 avril 2024 09:47
À : Alexis Vaillant-Gamache <[liaison@culturemauricie.ca](mailto:liaison@culturemauricie.ca)>
Cc : Stéphanie Cossette <[projet@culturemauricie.ca](mailto:projet@culturemauricie.ca)>
Objet : Re: Affichage des nouveaux ratios fournis par Footlight
 
Salut Alexis,
 
En fait, on vient de m'informer que le ratio/dimension des images thumbnail de Footlight n'est pas toujours le même, voilà pourquoi ça ne s'affiche pas comme vous le souhaitez. 

Voici un exemple : 
Voici l'image : https://cdn.footlight.io/iiif/3/1d2a8ba7-4dc2-4b92-b7f9-0c096d66054b.jpg/180,0,840,630/623,/0/default.jpg
 
Et un autre :
Voici l'image : https://cdn.footlight.io/iiif/3/41c1ee76-61bd-4f5e-a97e-98df74da5f69.jpg/0,183,2560,1340/623,/0/default.jpg
 
Vous remarquez qu'ils n'ont pas le même ratio, alors que 2 sont dans thumbnail !!!

### **ENGLISH TRANSLATION BELOW**

From: Delisle-Rivest, Maxime-Julien <[maximejulien@acolyte.ws](mailto:maximejulien@acolyte.ws)>
Sent: 15 April 2024 09:47
To: Alexis Vaillant-Gamache <[liaison@culturemauricie.ca](mailto:liaison@culturemauricie.ca)>
Cc: Stéphanie Cossette <[projet@culturemauricie.ca](mailto:projet@culturemauricie.ca)>
Subject: Re: Display of new ratios provided by Footlight
 
Hi Alexis,
 
I've just been informed that the ratio/size of Footlight's thumbnail images is not always the same, which is why they don't display the way you want. Here's an example: 

Here is the image: 

![Image](https://github.com/culturecreates/footlight-app/assets/45608438/426d58b1-694d-4148-af4d-43251260d398)

https://cdn.footlight.io/iiif/3/1d2a8ba7-4dc2-4b92-b7f9-0c096d66054b.jpg/180,0,840,630/623,/0/default.jpg
 
And another one :

Here is the image: 

![Image](https://github.com/culturecreates/footlight-app/assets/45608438/caa2aba9-3de4-4460-8762-2c325c8fbc68)

https://cdn.footlight.io/iiif/3/41c1ee76-61bd-4f5e-a97e-98df74da5f69.jpg/0,183,2560,1340/623,/0/default.jpg
 
Notice that they don't have the same ratio, even though 2 are in thumbnail !!!

@sahalali It is clear that the 2 image ratios are not the same. Can you please look into the problem and propose a fix.

Many thanks.

**Comment by saumier** [comment] 2024-04-16 03:29
@sahalali  The web company for culture-mauricie (Acolyte)  found this image thumbnail in the event “Alejandra Basañes : Terre de femmes”  https://api.footlight.io/events/6604409414060600645ff6e9
It looks to me like the image is not updating to the new aspect ratio of roughly 2:1.  I checked in staging and the old settings are still there and it looks like the old aspect ratio of 4:3.  Could there be a bug on our side where the images don’t update to a change in aspect ratio?

**Comment by sahalali** [comment] 2024-04-16 10:22
The root cause of the issue is that the image dimensions persist once the user edits the image. The xCordinate, yCordinate, width, and height values for Thumbnail and large images are identified based on the image settings in the calendar at that time.
Once, the image settings (maxWidth and aspect ratio) are updated, the event.image property should be updated by removing stored coordinates, width, and height.

Example:

`"image": {
    "large": {
      "xCoordinate": 40,
      "yCoordinate": 0,
      "height": 630,
      "width": 1120
    },
    "thumbnail": {
      "xCoordinate": 180,
      "yCoordinate": 0,
      "height": 630,
      "width": 840
    },
    "original": {
      "entityId": "1d2a8ba7-4dc2-4b92-b7f9-0c096d66054b.jpg",
      "height": 630,
      "width": 1200
    }
  }`

Workaround:
As a workaround, large and thumbnail details are now removed from staging. This will fix the issue for now. 

IMPACT:
1. This will impact the event images on the website and may lead to losing the image edit activity done by the user.

Long term fix:
We will require an API that either clears the image cordinates or implements a logic in the backend to auto-select the mid position of the image to avoid showing the top left corner of the image.

Note: The Image settings updation is a rare activity(in my view).

cc @saumier @troughc

**Comment by sahalali** [comment] 2024-04-16 12:15
@sahalali Will work on creating a matrix to record what is the impact of the current workaround.

**Comment by sahalali** [comment] 2024-04-17 10:15
@dev-aravind Can you please find the number of events affected by the workaround? Please prepare a sheet with its event-id and title.

**Comment by sahalali** [comment] 2024-04-17 10:22
@dev-aravind Please work on the long term fix for this issue.
Use case:
A user edits the image settings in the calendar(either aspect ratio or max-width is changed). 

UI: Show a warning before calling the update API.

Backend: If any change in image settings is identified, then remove all configurations (image.thumbnail, image.large fields) from images within all events from the calendar.

**Comment by dev-aravind** [comment] 2024-04-17 12:22
@troughc You can find the list of events affected [here](https://docs.google.com/spreadsheets/d/1G-wnEroBpoTtDMma9SMcfD6hihuVN20yaBz2o9MYkT4/edit?usp=sharing).

**Comment by troughc** [comment] 2024-04-17 16:02
@dev-aravind when I checked some the images (events) that are affected in STAGING, the image wasn't there at all (broken image). It is there in PRODUCTION. 

Does this mean all those events will have broken images when you implement the fix in Production? Because there are 115 affected events and that wouldn't be feasible since they were all imported by an aggregator...
Would we have to reupload the images for those 115 events? I just want to understand what the expectation/result of implementing a fix. 

### Example of broken image: DANSEncore event:


Staging 
link to event: https://staging.cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/6616eb1814060600646a0254

 
<img width="652" alt="Screenshot 2024-04-17 at 11 56 29 AM" src="https://github.com/culturecreates/footlight-app/assets/64489312/9f32cf44-36c3-4349-be2e-74ae4180b08b">

vs PRODUCTION 
link to event: https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/6


<img width="683" alt="Screenshot 2024-04-17 at 11 56 36 AM" src="https://github.com/culturecreates/footlight-app/assets/64489312/d440bde8-892f-4ebe-a6f0-06140c986c4c">

**Comment by dev-aravind** [comment] 2024-05-16 12:49
@troughc This is to be tested as part of #635

**Comment by troughc** [comment] 2024-05-16 23:08
How do I test this @dev-aravind ? can you please provide steps? thanks.

**Comment by dev-aravind** [comment] 2024-05-17 12:06
@troughc If you remove or modify the image configuration, the images which have a configuration will have their configurations removed (The coordinates of cropping). So they will look misaligned and will appear as if they were not cropped in the first place.

**Comment by troughc** [comment] 2024-05-17 17:50
Tested in https://pr-1103.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/events?page=1&order=asc&sortBy=upcomingEventDate on chrome
PASSED (to the best of my knowledge).

**Closed** 2024-06-21 14:51 UTC
Labels: bug, Mauricie, Customer request
