### ISSUE TITLE
User Screens

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#564] opened 2023-09-06 14:06 UTC
1. Here is the link to the user settings: https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=4205-98574&mode=dev

2. And here is the link to the calendar settings: https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=4205-98575&mode=dev. --> OUT OF SCOPE
```[tasklist]
### Listing Page.
- [x] Setup settings page layout
- [x] Create listing card, configure navigation for listing cards and implement tooltip options.
- [x] Toolbar: Implement add, clear, sort buttons and dropdown menus
- [x] Implement filters: status and user types.
- [x] Api integration.
- [x] Testing
```

```[tasklist]
### Add/Edit page
- [x] Set up page layout.
- [x] Create content UI
- [x] Implement Organization search.
- [x] Implement Calender search
- [x] API integration.
- [x] Testing
```

```[tasklist]
### Read only page
- [x] Setup page layout.
- [x] List details of user: UI
- [x] API integration
- [x] Testing
```

```[tasklist]
### Changes after updates in Get User api
- [x] User api search implementation in event listing page
- [x] UserName update in read only pages
- [x] UserName update in entity listing pages
- [x] UserName update in Navigation header
```

```[tasklist]
### Peer review for listing page
- [x] Access listing page using admin and guest account. Check onclick for card and tooltip are disabled for guest users
- [x] from an admin account check if all the functionality listed in tooltip works. Functionality include delete, go to edit page, activate/deactivate, copy invitation link
- [x] check if sort works
- [x] check if filters and pagination works
```

```[tasklist]
### Peer review for Read only page and edit page
- [x] Using an admin account click on one of the listing cards and go to Read only page
- [x] click on the edit user button to go to edit page. Check if all the details are loaded.
- [ ] change user datails and submit
- [ ] reload again to check if details have updated or not
- [ ] Login from an account with multiple calendars. Click on leave button. reload the page to ensure the person left the calender successfully.
```

```[tasklist]
### Peer review for Add user
- [x] Click add button from listing page to goto add user page
- [ ] Add user credentials and submit.
- [ ] Go to email and accept invitation. Come back to listing page and ensure the user is present.
```

**Comment by sahalali** [comment] 2023-09-06 14:09
@SyamBabu-M   Can you please create subtask and prepare the estimates?

**Comment by SyamBabu-M** [comment] 2023-09-07 12:06
REACT_APP_FEATURE_FLAG_USERS=true
is the feature flag

**Comment by saumier** [comment] 2023-09-07 16:55
@SyamBabu-M Please add a link to the estimate document you prepared. Thx.

**Comment by sahalali** [comment] 2023-09-08 09:59
Reference: https://docs.google.com/spreadsheets/d/10r3v9TJ3iGhfSl4wqFzFGTdJ7u3RqrDLID_0EkzEQgs/edit?usp=sharing

**Comment by saumier** [comment] 2023-09-15 13:41
In today's standup @SyamBabu-M raised a concern that there are more API changes needed support User pagination and filtering. Beginning of next week Syam and Suhail will update the work estimate.

**Comment by sahalali** [comment] 2023-09-18 05:37
API changes required.
1. Modify Entity listing API (events, place, org, person) response changes.
2. Modify user listing API response - add invited by user name.

Backend changes will require 1 hour. This will be done today.

**Comment by SyamBabu-M** [comment] 2023-09-18 06:43
@saumier @troughc @sahalali 
@dev-aravind has completed #616. Since it contains some significant changes, other places that have used this API need to be updated. I will describe the tasks under the sub-tasks section.
Since from now onwards, the username is stored in the backend, the current implementation of calculating the username in the front end needs to be updated.
Taking all of these changes into account, I have estimated an additional 14 hours for the ticket.

**Comment by troughc** [comment] 2023-09-21 14:25
Hi @SyamBabu-M I added the default text in the Foolight CMS copy spreadsheet.

**Comment by SyamBabu-M** [comment] 2023-09-25 15:09
@troughc @saumier @sahalali 
As we discussed in today's standup,
- I will hide the Organization select option from the Add/Edit user page.
- I will also change the search calendar option to a list of calendar cards with an option to permit the user to leave the calendar. 
- The user edit screen that is accessed from the navbar will now be updated with the new Edit user page.

The full design can be implemented once the API changes are made. We will discuss with the team about the changes in the invite and update the user API with the team. And since new will be created for these, I will take it up in the future.

**Comment by saumier** [comment] 2023-09-25 16:41
@SyamBabu-M Just a reminder that the spirit of this epic is to release by the end of October a "merged" CMS that replaces Old CMS so our clients no longer need to use Old CMS. If any blockers come up from trying to follow the Figma exactly, then we should discuss how to remove the blockers to achieve our epic :-)

**Comment by AbhishekPAnil** [comment] 2023-09-25 18:00
@troughc  Created a separate issue to handle multiple calendar invites in frontend.
https://github.com/culturecreates/footlight-app/issues/619

**Comment by troughc** [comment] 2023-09-25 19:18
> ...Do you want me to show a validation failed message for each field in the form when an admin tries to add a new user without filling in the required fields...
.....add the message to be shown when a user is successfully deactivated/activated, the invitation ID of a user is copied, and a user is deleted....
In the user Add/Edit page message to show when the user leaves the calendar is not given.

@SyamBabu-M I have added the missing copy to the Footlight CMS copy document and tagged you (using comments):
- Added the validation fail messages for required fields
- Added user listing messages (right-click menu). Note that I didn't add anything for "when a user is successfully deactivated/activated" because the UI will update to show them that it worked (just like when you publish/unpublish an event - there is no message).
- Added a row for the "Leave" button - includes French translation of the button and  the message to display when a user clicks 'Leave'.

**Comment by SyamBabu-M** [comment] 2023-09-26 05:17
@dev-aravind Please add calender logo and calender names in get user by ID API

**Comment by AbhishekPAnil** [comment] 2023-09-28 07:11
@SyamBabu-M 
Tested in staging: **User listing page**.The functionalities works fine but there are minor css changes needed.
Issues found : 
1.Change Invited By to Invited by."B" is in lower case.


![Image](https://github.com/culturecreates/footlight-app/assets/117100211/d5258f19-cbc9-473b-a01a-99acf53cf2de)


2.Change text for inactive to Deactivated. and follow the same order in figma .Also show the tick mark  and higlight it once the user selects an item.
CMS.


![Image](https://github.com/culturecreates/footlight-app/assets/117100211/d651abd8-9145-4267-9613-cc90c069d636)

Figma 


![Image](https://github.com/culturecreates/footlight-app/assets/117100211/aa80c8a6-e5a4-449f-9028-dcaf801e6dfc)

**Comment by AbhishekPAnil** [comment] 2023-09-28 07:36
Read only page:Tested in staging 
Issues found:

1.Add the roles button to the calendar listed in the bottom.
CMS


![Image](https://github.com/culturecreates/footlight-app/assets/117100211/b3dce713-fdaa-4695-a620-5a0536921688)

Figma 


![Image](https://github.com/culturecreates/footlight-app/assets/117100211/37ee466d-14a3-4847-b1d8-a60a4c228f61)

**Comment by AbhishekPAnil** [comment] 2023-09-28 08:17
Edit page : Tested in staging.

Issues Found:
1.When I update the details of an existing user in edit page ,I am redirected back to the respective users read only page.But the changes done in the edit page is not reflected in read only page.
Steps to reproduce:
i.Select an existing user
ii.Go to the edit page from the read only page.
iii.Change the interface language.
iv.Redirected back to read only page but the Language preferred is not changed.

Expected behaviour : The language should be changed to the one that was updated in edit page.

2.The size of the admin role button shown in the calendar section is large compared to the ne given in figma.
CMS


![Image](https://github.com/culturecreates/footlight-app/assets/117100211/073611fd-2970-434c-b156-e03e042b864b)

3.Leaving a calendar doesn't work as expected .I had access to two calendars tout culture and signe laval.I left the tout culture calendar.The api request was successful .When I come back to the dashboard I have only access to single calendar "signe laval" which is good and working as expected.But when I go to the user profile page,the calendar section shows two calendars.Signe laval and tout culture which shouldn't be happening .I checked the api response of the current user and it had two calendars.Somehow  the backend is not updated properly in this case.

**Comment by AbhishekPAnil** [comment] 2023-10-03 11:49
Tested in staging:
1.Invited By changed to Invited by : PASSED.
2.inActive changed to Deactivated: PASSED.
3.Roles button added to user read only page : PASSED.
4.Size of role button in edit page corrected : PASSED.
5.Changes in the edit page is reflected in the read only page: PASSED


Not passed :
Leaving the calendar still doesn't work properly for me.The previous bug still exists.

**Comment by troughc** [comment] 2023-10-03 16:54
Testing in staging (after doing a hard reset):
**As an Admin in Signe Laval calendar / in the Tout Culture Calendar**
User listing
1. invite a user: **DID NOT PASS**  
- couldn't test. When I click + User, the system hangs for more than 20 seconds (I see a spinner). I never get to the screen (gave up after a minute)
2. Sort by first name / last name / username: PASSED
3. Search: PASSED
4. Various filters: PASSED
5. Right-click menu - Copy invitation link: **DID NOT PASS**
- doesn't seem to do anything at all (doesn't copy)
6. Right-click menu - User status filter vs Display of user status: **INVESTIGATION NEEDED**
- Please look at this user: http://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/settings/user-management/64663801af1c5500656da1fd 
-There are two Anyssa Doiron users (same name) but different emails. In the OLD staging CMS they are both 'pending'. In the NEW STAGING CMS, the one above (URL link) is displayed as ACTIVE. However, in the NEW STAGING CMS, the user is included in the INVITED filter. The filter is right, the tag saying ACTIVE is wrong.
<img width="1142" alt="Screenshot 2023-10-03 at 12 06 31 PM" src="https://github.com/culturecreates/footlight-app/assets/64489312/1e90016f-8e31-474b-882b-70583e7f5622">
This issue is also sporadically happening with the Right-click menu option "activate/deactivate" but i seemed to be able to get around it by changing that status a few times.  However, I am not confident that it is working properly.
7. Deleting a user: PASSED
8. Deactivating a user in one calendar and beign able to log into the other calendar: DID NOT PASS
Steps to reproduce: 
1. As an Admin, I deactivated my guest user 'etroughton(guest)' for Signe Laval.  
2. I logged out my admin user.
3. I tried to log in as etroughton(guest) - I am a guest user in the Tout Culture calendar. 
4. I did not appear to log in. Instead, this error appeared:
<img width="1102" alt="Screenshot 2023-10-03 at 12 25 00 PM" src="https://github.com/culturecreates/footlight-app/assets/64489312/7ea0cae0-397d-4510-a5f5-96905b114de3">
5. I could not do anything after that - I always got that error when I tried to go back to the login page of the CMS - therefore I couldn't access it to log in to a different profile (ADMIN)
**Expected behaviour:** I should have been logged into the other calendar as etroughton(guest) - because I am a member of the other calendar (Tout Culture).

Additional potential issue: the only way I could get back into the CMS (even as an ADMIN) was by logging into the Old CMS (staging) as my  ADMIN user, and re-activating etroughton(guest) on the Signe Laval calendar.  
Only then was I able to 'back' out of the error. When I clicked Back, the Signe Laval calendar was displayed  and I was already logged in as the guest (even though it failed).

**Comment by troughc** [comment] 2023-10-03 17:29
Testing user settings leaving a calendar as a guest (staging on Chrome): 
User list: 
Can I see the list? yes
When I hover over any user, the little hand appears so it looks like I can click them. Expected behavior with the hand is that I can click. This is not the case (so the hand should not be displayed)
Can I click my own user in the list when I am a guest? No. 
All the above raises the question for me as to whether we should display the user list to people who cannot do anything with it. @saumier I would like to discuss with you before deciding.

User leaving a calendar (guest profile)
Steps: 
Go into my profile via top navigation (I was in the Signe Laval calendar)
Leave the Signe laval calendar. The Calendar dropdown in the left navigation now displays Tout Culture: GOOD
<img width="957" alt="Screenshot 2023-10-03 at 1 23 37 PM" src="https://github.com/culturecreates/footlight-app/assets/64489312/ec088e91-4db7-4d71-acd2-318b67456cc3">
However the Signe Laval calendar is still there:

<img width="1318" alt="Screenshot 2023-10-03 at 1 23 25 PM" src="https://github.com/culturecreates/footlight-app/assets/64489312/5ef7b9fe-85de-464e-8309-106b4baabcee">

I can select Signe Laval and I get this error and can get stuck (I can't back out of the error easily): 

<img width="1259" alt="Screenshot 2023-10-03 at 1 24 14 PM" src="https://github.com/culturecreates/footlight-app/assets/64489312/bbe15a2d-d272-461d-9e6a-0031e97ef432">

**Comment by troughc** [comment] 2023-10-04 21:17
@SyamBabu-M here is my test feedback. It looks really great, only a couple small issues (listed first). @saumier I leave it to you to decide if the popup issue should be logged separately. 

**Adding a new user: one issue with the popup.**
When I'm trying to add a new user, the popup for the first name stays in the way - I can't get it to disappear (and more than one person can have the same first name). 
Expected behavior, I can add a first name and then press enter (or click away) and the pop up closes - and the rest of the fields remain blank.
![Image](https://github.com/culturecreates/footlight-app/assets/64489312/5c8fd51e-9d84-4959-a532-2295814f5be4)
**Right-click menu - Copy invitation link:** Still doesn't work for me.  I am okay with you logging this in a separate issue. Maybe @saumier should test this specific issue (copy invitation)



Viewing my own profile from the settings view: PASSED
User status filter vs Display of user status: PASSED
Leaving a calendar and still staying in the other one - and being able to log in (with only one calendar showign in the left navigation: PASSED
Invite a user: PASSED
logging in after being invited: PASSED
NOTE (will log this as a separate issue): the invitation I recieved was to an 'undefined' calendar (in the subject line and in the body text). I think that @SuhailAliyar knows how to fix this....this email problem should be treated as a separate issue (that I think may already exist).

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/7369c82b-af27-4235-965c-0ebe5ed91106)


YAY,  Syam, please ask Gregory to close this issue if you log the popup problem and copy invitation link separately.

**Comment by troughc** [comment] 2023-10-04 23:02
One more thing @SyamBabu-M, When I look at my profile as an admin, it looks like I can change my user type (from Admin). This should be greyed out in my opinion. The Admin should not be able to change their profile (because they will block themselves from full access to their calendar).

@saumier @sahalali , can you confirm? The Admin should not be able to change their user type (unless I am forgetting that we made a different decision about this).
thanks!

**Comment by saumier** [comment] 2023-10-05 13:24
@troughc This works in HTTPS. 

> Right-click menu - Copy invitation link: Still doesn't work for me. I am okay with you logging this in a separate issue. Maybe @saumier should test this specific issue (copy invitation)

**Comment by saumier** [comment] 2023-10-05 22:18
Bug: Missing display of Last name in read-only. Expected behaviour is to see the last name field on the read-only page.



![Image](https://github.com/culturecreates/footlight-app/assets/419491/607182fc-e9a2-47e4-a1ae-963c13e30cea)

**Comment by SyamBabu-M** [comment] 2023-10-06 04:55
@saumier Earlier we were creating username from frontend itself. Recently we added a username field in db, so the username seen in the userListing pages and  in other entity listing pages are the one coming from the backend. But in the navigation bar we were still using the old method to find the username. This is what caused the mismatch.

**Comment by SyamBabu-M** [comment] 2023-10-06 04:55
@dev-aravind Please add userName to the login api response.

**Comment by dev-aravind** [comment] 2023-10-06 07:22
@SyamBabu-M It's up in staging right now.

**Comment by troughc** [comment] 2023-10-10 21:44
Tested Staging on Chrome 
Right-click menu - Copy invitation link in https:// version: PASSED
Adding a new user, the popup for the first name is no longer in the way: PASSED
Last name included in read only page: PASSED
My username (ctroughton) appears correctly in the list (without a '1' appended): PASSED

**New Issue:** Click my own name in the User list page to view the profile - get sent to an error page. 
Steps to reproduce.

1. Log in as an admin
2. Find your user profile in the User Mangement list (in Settings). 
3. Scenario ONE: Use the right-click menu to edit it. This works taking you directly to the Edit profile page. PASS
4. Scenario TWO: In the user management list, click your user profile. This does not work. Instead, a 404 error page appears. 
5. Now, do one of the following:
- Click the Back button displayed in the error page. You go back to the user management list (in settings).
- Click the back arrow in your chrome browser. You go to the Edit page for your own user profile where you can edit it ?

**Comment by troughc** [comment] 2023-10-16 17:10
Tested Staging in Chrome: PASSED

**Closed** 2023-11-01 02:01 UTC
Labels: bug, feature
