### ISSUE TITLE
Migrate PLACES form configuration to "forms" field

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#837] opened 2023-12-04 22:11 UTC

**Comment by sahalali** [comment] 2023-12-06 10:46
@troughc is this duplicate of https://github.com/culturecreates/footlight-calendar-api/issues/780

**Comment by troughc** [comment] 2023-12-06 13:14
No @sahalali this is not a duplicate, this is for places.

**Comment by AbhishekPAnil** [comment] 2023-12-06 13:26
@sahalali Right now ,we are using the formSchema for Places in UI.We need to migrate to the forms in the UI.When I checked the staging, we already have the fields for Places inside the "forms".So the backend migration is already done I guess.The only change required would be in the frontend.

**Comment by AbhishekPAnil** [comment] 2023-12-06 13:31
@AbhishekPAnil Please estimate this.

**Comment by AbhishekPAnil** [comment] 2024-01-24 12:51
Since we are implementing  data centric approach for Places form,we don't need to implement anything in the formSchema .Hence we don't need this issue.The only changes needed in the backend are adding the missing fields inside the forms json .

**Closed** 2024-06-21 14:47 UTC
Labels: wontfix
