### ISSUE TITLE
Slow load of Places in Staging

### ISSUE THREAD

**Issue by kmdvs** [culturecreates/footlight-app#1297] opened 2024-09-02 08:00 UTC
Testing in Staging, I repeatedly had slow loads in editing a Place

See Options requests of 9.6s
![Places tests - slow load](https://github.com/user-attachments/assets/45e93508-4f7b-4975-b6d7-51f8990f8314)

Steps: (using "Inspect" in the browser and choosing the Network tab, get the requests info)
Go to Places
Filter with "admin"
Choose a Place
Repeat a few times: sometimes fast, but some (like the example above) are slow 

This affects clients... It also makes Cypress regression tests fail intermittently (a cutoff right now is at 4s for any page request). 

According to chatGPT 4o (aggregate of what's found on the web):

### General Guidelines for Acceptable Wait Times:
Page Load Time:

**Under 2 Seconds**: This is often considered the ideal target for page load time. Users generally expect a page to load within 2 seconds. This benchmark is particularly important for e-commerce sites, landing pages, and other high-traffic websites where user engagement is critical.
**2 to 5 Seconds**: Still acceptable, but anything beyond 3 seconds starts to impact user satisfaction. Some users may begin to lose patience, especially if they are accustomed to faster sites.
**Over 5 Seconds**: This is generally seen as too slow for most commercial applications. At this point, users may abandon the page or become frustrated, leading to a poor user experience.

**Comment by troughc** [comment] 2024-09-03 15:21
Thanks @kmdvs, the analysis makes sense to me! Assigning to @sahalali

**Comment by sahalali** [comment] 2024-09-05 09:28
When loading a place page, the response times are stable at 300-600 ms. I doubts this might be happening when a large number of API calls are done. 

@saumier Can we do a load testing for place listing?

**Comment by saumier** [comment] 2024-09-06 16:09
@SuhailAliyar My main big concern with this issue is not about slowing down users, but rather about the Cypress regression tests failing intermittently. It is very important that the Cypress regression tests consistently run in a closed environment.  However, since Kim was hitting staging which could be having other load issues in parallel, I would suggest you redo the Cypress regression tests in a Github runner (with no outside interference) and see if this problem occurs intermittently. Until the Cypress regression tests run consistently in a closed environment with the same data and same code, we cannot have confidence in the process.

**Comment by sahalali** [comment] 2024-10-07 04:43
@dev-aravind Can you please see why the test fails on Chrome after the update? Can you please align with Kim if needed today?

**Comment by dev-aravind** [comment] 2024-11-11 11:54
@sahalali This issue can be closed as we decided to move forward with Firefox only for our tests.

**Closed** 2024-11-14 12:01 UTC
