### ISSUE TITLE
Enhancement: user settings: link user profile to organization(s)

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#831] opened 2023-11-30 00:37 UTC
As an admin, I want to link user profiles with one or more organizations so that the person I am inviting to my calendar can edit these organizations, whether they created them or not.
As the invitee, I can see the organization in my user profile, but cannot change it.

This is also a step towards developing a Teams feater where users could work together on events/places/orgs/people.

Updated Figma link: https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=4205-98574&mode=dev

- new section for Admin, outlined in red. there are a couple comments also.
- Caitlin can present if needed.

Note: there os an issue previously created for the Old CMS here: https://github.com/culturecreates/footlight-admin/issues/102

cc @saumier

**Comment by AbhishekPAnil** [comment] 2023-12-06 11:03
UI Tasks: 8.5h
1.Add the check for users if they have access to the organization both in listing ,read only and edit organization page.-4h
2.Add the UI layout to add organizations to user edit page.-2h
3.Add the api integration to add the organization access for an user in user edit page.-2h
4.Create organization from artsdata .(Optional)-0.5h

**Comment by sahalali** [comment] 2023-12-06 11:04
1. Update User Data model - 4 H
2. Update GET and POST /users/{id} to add/update organizations: 4H
3. Add support to create an organization with external-source URI while updating user - 8H (Optional)
3. Update user authorization: to let GUEST and CONTRIBUTOR users update the organization that the user is a member of. - 4H
4. Unit testing (if not too complex to implement) - 8H
5. UI changes - 8.5H

Backend estimate: 36.5H

**Comment by AbhishekPAnil** [comment] 2024-02-13 13:27
@sahalali 
There is a mismatch in the calendarId in the response of 
curl -X 'GET' \
  'https://staging.api.cms.footlight.io/users/current' \
  -H 'accept: */*' \

`{
  "id": "644940c5c54c9f0064e2ce9a",
  "firstName": "Abhishek",
  "lastName": "P Anil",
  "email": "abhishek@culturecreates.com",
  "userName": "ap anil",
  "interfaceLanguage": "EN",
  "profileImage": "https://www.gravatar.com/avatar/e64e20bf65ce699037d641a1adb50cfa?d=https%3A%2F%2Fui-avatars.com%2Fapi%2FAbhishek%2BP%2BAnil",
  "roles": [
    {
      "role": "ADMIN",
      "calendarId": "63457978637093005071a053",
      "invitationId": "644940c5c54c9f0064e2ce94",
      "invitedBy": "Gregory Finch",
      "status": "ACTIVE",
      "invitedByUserId": "630a76e033ffa200728336c3",
      "invitedOn": "2023-04-26T15:18:29.534Z",
      "name": {
        "fr": "Tout culture",
        "en": "Tout culture"
      },
      "image": {
        "uri": "https://cdn.footlight.io/iiif/3/tout-culture-logo.png/0,0,1620,1080/400,/0/default.png"
      }
    },
    {
      "calendarId": "6308ef4a7f771f00431d939a",
      "role": "ADMIN",
      "status": "ACTIVE",
      "invitedBy": "Gregory Finch",
      "invitedByUserId": "630a76e033ffa200728336c3",
      "invitedOn": "2023-05-05T12:30:51.806Z",
      "invitationId": "6454f6fb127fe0006438ddd0",
      "name": {
        "fr": "Signé Laval",
        "en": "Signé Laval"
      },
      "image": {
        "uri": "https://cdn.footlight.io/iiif/3/signe-laval-logo.png/30,200,1620,1080/400,/0/default.png"
      }
    }
  ]
}`

**Comment by sahalali** [comment] 2024-02-14 06:30
The issue is now fixed and deployed in production and staging

**Comment by AbhishekPAnil** [comment] 2024-02-14 12:29
@sahalali There is a mismatch in the calendarId in the response of
curl -X 'GET'
'https://staging.api.cms.footlight.io/users/current'
-H 'accept: /' \

The response is missing "roles" key value .

**Comment by dev-aravind** [comment] 2024-02-15 09:21
@AbhishekPAnil I did my first round of peer review for this and had these issues:

1. I was not able to edit an organization while logged in as a guest/contributor user who has access to that organization.
2. I was not able to change the roles of a guest/contributor while logged in as an admin.
3. If I demoted myself from admin to guest, I was still able to edit any organization unless I logged out and logged back in.
4. The search API was showing organizations from external sources. For now we are not using external sources.

**Comment by AbhishekPAnil** [comment] 2024-02-15 12:14
> [@sahalali](https://github.com/sahalali) curl -X 'GET' 'https://staging.api.cms.footlight.io/users/current' -H 'accept: /' \
> 
> The response is missing "roles" key value .

This doesn't seems to be an issue.Its working fine 
cc @AbhishekPAnil

**Comment by SyamBabu-M** [comment] 2024-02-16 10:30
@AbhishekPAnil I peer reviewed this.
1:  Issue with not being able to change the roles of a guest/contributor while logged in as an admin. - fixed
2:  If I changed my role from admin to guest I can edit only organizations that I am part of. - fixed
3: Issue with search API showing external organizations - fixed

New issues found:
1: The user cannot leave the current calendar. I logged in as a guest and tried logging out is got the 400 error "with error message "Calendar id is mandatory in the header." Same thing happens when trying to leave any calendar.
2: Cannot change the language. The whole app crashes. When I try to open app from incognito loads but trying to save user details again causes it it crash.

**Comment by SyamBabu-M** [comment] 2024-02-16 11:38
@AbhishekPAnil  I did a second round of peer review.
1: The user cannot leave the current calendar - fixed
2: Cannot change the language. - fixed

New issue found: 
1: @sahalali I suspect this is a backend issue. After I leave all calendars and try logging in to the same account. I got a 200 response from the backend for login API. This persisted for some 30- 40 min, after that, I was getting the correct 404 response.

<img width="1432" alt="Screenshot 2024-02-16 at 5 07 33 PM" src="https://github.com/culturecreates/footlight-app/assets/139208017/40182bbe-3386-491b-89f8-75b553f0fb9c">

**Comment by sahalali** [comment] 2024-02-16 12:18
The issue is now fixed. The edge case related with changing the userStatus when the user leaves all calendar.
If the user is not an active member of any calendar, then the userStatus would have been INACTIVE and login should be denied.

**Comment by SyamBabu-M** [comment] 2024-02-19 11:44
@AbhishekPAnil I did another round of peer review

Issues found - 
1 - when a user with access to 2 calendars tries to leave the current calendar he gets an error message.

![Image](https://github.com/culturecreates/footlight-app/assets/139208017/236d43b8-6f02-4a63-98e7-b880f8958fc2)

**Comment by troughc** [comment] 2024-02-22 18:01
Tested in french and english in chrome.
1. Admin can add org to another user (I did my guest user): PASS
2. Admin can invite user and add org: PASS
3. Admin can change another user role: PASS
4. Guest user can edit the associated organization: PASS
5. Guest- calendar information section is read only for guest profile: PASS
6. Guest can leave a calendar with the Leave button: PASS
7. All users - 2 points of access to profile is consistent (my profile or by user settings): PASS

One issue that I found:
in Tout Culture, the organization name at the top seems to always be in English even when I am viewing the French UI.  Maybe this is unrelated to this issue, but please check.
steps to repeat:
1. create a different name in french than english for an organization.
2. view the ui in french
3. the english name is at the top.

Guest user logged in french UI
![Image](https://github.com/culturecreates/footlight-app/assets/64489312/1eed0978-24dc-473f-8a18-05c822d90f36)


top of page is in english. This is also the name that appears in the listing page (english) in french ui
![Image](https://github.com/culturecreates/footlight-app/assets/64489312/9aa7f329-560f-4fdc-a47c-f12b62535bfc)

**Comment by troughc** [comment] 2024-02-22 19:56
Update: I have decided to separate the bug mentioned above into another issue and set this as ready to deploy
cc @AbhishekPAnil

**Comment by AbhishekPAnil** [comment] 2024-02-23 05:04
> [@AbhishekPAnil](https://github.com/AbhishekPAnil) if the above mentioned issue should be logged separately, please let me know and we can set this one to be deployed tomorrow. thanks!

Yes this should be logged separately.

**Closed** 2024-02-23 07:07 UTC
Labels: Customer request, To be deployed
