### ISSUE TITLE
NAC Osaka prod calendar - duplicate event bug

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1453] opened 2024-11-20 19:00 UTC
This seems to only be an issue in the NAC Osaka prod calendar. When I try to duplicate an event, I get an error message.
Steps to reproduce
In list view, click to open the menu next to an event and chose duplicate event.
The event form opens. Click save as draft. 
This error appears:
![Image](https://github.com/user-attachments/assets/43cca023-ea28-468c-9538-bc5da8bdd442)

**Comment by AbhishekPAnil** [comment] 2024-11-21 06:11
Bug Report:
An error was triggered by the backend when attempting to save an event as a draft.

The payload for creating the event included:
"organizers": [{"type": "Organization"}]
The organizers field was missing an entityId.

This issue occurred because the event being duplicated also had an organizer without an entityId:
[Event Link](https://staging.api.cms.footlight.io/events/673762cbad60100064a3caae)

To resolve this, I have added an additional check in the frontend to remove any organizer, person, or supporter without an entityId. This ensures that the payload for event creation or updates does not include any organizers, persons, or supporters lacking an entityId.

@sahalali I assigning this to you,to make the correction in the Backend.

**Comment by sahalali** [comment] 2024-11-26 11:06
The issue in the backend was that the organization/person importing from Artsdata wasn't getting pulled to CMS, instead the source URI was kept in the CMS. This was causing the issue. Now, the issue is resolved in staging.

**Comment by AbhishekPAnil** [comment] 2024-11-27 05:25
@troughc You can test this in the PR link

**Comment by troughc** [comment] 2024-11-27 16:47
Tested in PR: PASSED

**Comment by troughc** [comment] 2024-11-29 13:26
The regression test is failing. Please look into this.

**Comment by kmdvs** [comment] 2024-12-02 06:06
The RT aren't designed for other calendars than Tout Culture... At least, not yet, since I never tested another calendar... It would be great to give my 4 accounts access to all calendars, so I can actually make appropriate changes based on what calendar IS tested. In theory, since the code-base for all calendars is pretty similar (correct me if I am wrong), and the RT use the UI, and the UI don't change that much between calendars, nothing suggests a specific calendar should pose a particular problem other than small exceptions (like clicking on an additional button to edit something, or using an additional drop-down before saving an event). 

I would need specific information on what fails to investigate, and more importantly, access to all calendars for my 4 accounts in production :)

**Comment by sahalali** [comment] 2024-12-02 06:36
I am creating a separate ticket to address this issue since the RT failure is not directly dependent on this issue.

**Closed** 2024-12-03 05:49 UTC
Labels: bug, NAC
