### ISSUE TITLE
subEventConfiguration not getting updated for event series while editing an event(CMS) .

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#1178] opened 2024-06-21 12:57 UTC
For an event series that is imported by the aggregator :
While updating the event from the CMS ,the recurring event configuration is updated right now. Instead of updating the recurringEvent the subEventConfiguration should be updated properly.

**Comment by dev-aravind** [comment] 2024-06-21 13:04
Related bug https://github.com/orgs/culturecreates/projects/2/views/1?filterQuery=dev&pane=issue&itemId=68301064

**Comment by sahalali** [comment] 2024-06-24 05:06
This is a duplicate of https://github.com/culturecreates/footlight-calendar-api/issues/1021

**Closed by sahalali** 2024-06-24 05:06 UTC
Labels: bug
