### ISSUE TITLE
Organization and Person Screens using data-centric approach

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#457] opened 2023-07-31 18:24 UTC
```[tasklist]
### Frontend-Organizations
- [ ] https://github.com/culturecreates/footlight-app/issues/481
- [ ] https://github.com/culturecreates/footlight-app/issues/482
- [ ] https://github.com/culturecreates/footlight-app/issues/483
- [ ] https://github.com/culturecreates/footlight-app/issues/484
- [ ] https://github.com/culturecreates/footlight-app/issues/471
- [ ] https://github.com/culturecreates/footlight-app/issues/472
- [ ] https://github.com/culturecreates/footlight-app/issues/473
- [ ] https://github.com/culturecreates/footlight-app/issues/474
- [ ] https://github.com/culturecreates/footlight-app/issues/486
- [ ] https://github.com/culturecreates/footlight-app/issues/475
- [ ] https://github.com/culturecreates/footlight-app/issues/476
- [ ] https://github.com/culturecreates/footlight-app/issues/477
- [ ] https://github.com/culturecreates/footlight-app/issues/478
- [ ] https://github.com/culturecreates/footlight-app/issues/479
- [ ] https://github.com/culturecreates/footlight-app/issues/485
- [ ] https://github.com/culturecreates/footlight-app/issues/487
- [ ] https://github.com/culturecreates/footlight-app/issues/488
- [ ] https://github.com/culturecreates/footlight-app/issues/540
```

```[tasklist]
### Frontend-People
- [ ] https://github.com/culturecreates/footlight-app/issues/506
- [ ] https://github.com/culturecreates/footlight-app/issues/507
- [ ] https://github.com/culturecreates/footlight-app/issues/508
- [ ] https://github.com/culturecreates/footlight-app/issues/509
- [ ] https://github.com/culturecreates/footlight-app/issues/510
- [ ] https://github.com/culturecreates/footlight-app/issues/511
- [ ] https://github.com/culturecreates/footlight-app/issues/513
- [ ] https://github.com/culturecreates/footlight-app/issues/512
- [ ] https://github.com/culturecreates/footlight-app/issues/514
- [ ] https://github.com/culturecreates/footlight-app/issues/515
- [ ] https://github.com/culturecreates/footlight-app/issues/516
- [ ] https://github.com/culturecreates/footlight-app/issues/517
- [ ] https://github.com/culturecreates/footlight-app/issues/518
- [ ] https://github.com/culturecreates/footlight-app/issues/519
- [ ] https://github.com/culturecreates/footlight-app/issues/520
- [ ] https://github.com/culturecreates/footlight-app/issues/521
- [ ] https://github.com/culturecreates/footlight-app/issues/541
```

```[tasklist]
### Backend Tasks
- [ ] Add the api to the get form field details according to the data centric approach
```

**Comment by saumier** [comment] 2023-07-31 19:21
@AbhishekPAnil Please add your estimate and tasklist based on your spreadsheet.


New organization search page | Create New organization search page
-- | --
Create/Edit New Organization | Create organization details page
Add organization image/logo
Edit organization details page

**Comment by AbhishekPAnil** [comment] 2023-08-16 07:52
Feature Flag :

REACT_APP_FEATURE_FLAG_EDIT_SCREEN_PEOPLE_PLACE_ORGANIZATION=true

**Comment by AbhishekPAnil** [comment] 2023-08-18 13:11
Referecnce doc:
https://docs.google.com/document/d/16lwHA-IKFEGOTml9_OJGROrm2Lmd8JIQIxMI15rNzzc/edit#heading=h.qtdqozjh9mrl

**Comment by SyamBabu-M** [comment] 2023-08-22 06:06
@SuhailAliyar Please add the link for "Arts data" to the get entities API as it is needed in the edit/create new entity search popover.

**Comment by sahalali** [comment] 2023-08-22 07:20
@SyamBabu-M I've added support to include source URI in the entity search API response for classes PERSON, PLACE, and ORGANIZATION.

Sample response:
```
[
  {
    "id": "648cd38d5526a70064506dff",
    "name": {
      "fr": "Brick et Brack"
    },
    "disambiguatingDescription": {
      "en": "Organization"
    },
    "type": "Organization",
    "uri": "http://kg.artsdata.ca/resource/K5-381"
  }
]
```

**Comment by saumier** [comment] 2023-08-22 17:04
@SuhailAliyar @AbhishekPAnil I discussed with Caitlin about the Places edit screen. She agrees to remove the search from City, Province and Country. It will work like in quick create where the address field is used to search Google places API and automatically fill in the street address, city, province, country and postal code and longitude, latitude. Also, the checkbox "sync to address" was also removed.  Caitlin will update the Figmas.

**Comment by saumier** [comment] 2023-09-01 13:09
@sahalali @AbhishekPAnil Lets meet on Monday after the standup to estimate the remaining work.

**Comment by saumier** [comment] 2023-09-06 14:49
@troughc We had a planning session today and propose the following:
22-SEP: Code complete with all features ready to test in staging
3-OCT: Recommended date to toggle on edit screens for client

We will also plan the User Screens to be code complete in September with a date to be confirmed in the coming days, and then work on Taxonomy screens to be code complete early October. We will be able to bring on a new client as of Nov 1st at the latest.

**Comment by SyamBabu-M** [comment] 2023-09-15 06:57
@AbhishekPAnil @dev-aravind  I have tested the Persons screen. There is an issue with the occupation field.
Steps to reproduce the bug:
- click a person. Go to the edit page
- Edit occupation.
- Save changes.
- Come back to the edit page of the same person. The previously added occupation will not be selected.

Apart from that every thing else is working fine.

**Comment by troughc** [comment] 2023-09-18 17:20
@SyamBabu-M I spotted a typo in the french screen (edit screen) for people -  there is an extra "A" at the beginning of the following sentence and "." (period) missing at the end. It should be like this: 


Ajouter pour différencier la personne dans les résultats de recherche.

**Comment by AbhishekPAnil** [comment] 2023-09-20 06:23
@saumier Currently we don't have support for adding social media links in the backend and this has not been included in this week's release.But if this is a priority we discuss about this in the stand up.

**Comment by saumier** [comment] 2023-09-20 13:28
@AbhishekPAnil @sahalali Moved Social Media links to another issue https://github.com/culturecreates/footlight-app/issues/596

**Comment by troughc** [comment] 2023-09-22 17:17
Test Organization in Chrome:
Signe laval website in the English UI shows a mixture of English French UI labels in the edit screen: 


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/f35a8079-ab10-450f-85d8-67c1df6a508e)

**Comment by AbhishekPAnil** [comment] 2023-09-25 12:57
I have fixed the above three issues and updated the same in staging.

**Comment by troughc** [comment] 2023-09-25 20:42
Test staging in CHROME:

### 1. Retested and fixed 

1. Signe laval website (mono-lingual website): the English UI shows a mixture of English French UI labels in the Edit screens for both Organizations and People. 
2. The organization "Académie de danse de l'Outaouais" now has a Place in all views. see https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/organizations/6451600fe19f7200646d1fca

### 2. Retested and not fixed
1. I search for a name (like Gregory Finch) and I find in in Artsdata. When I click the 'Artsdata' link in the dropdown search I go to a bad page. I go here: https://api.artsdata.ca/K1-3 instead of going here: http://kg.artsdata.ca/resource/K1-3

2. Typo in PEOPLE and ORGANIZATION Edit pages: In both PEOPLE and ORGANIZATION is a typo in the English UI - a period (.) is missing at the end of the following sentence:
**Add to differentiate organization in search results.**
Note that the period (.) is also missing from the equivalent sentence in the FRENCH page for PEOPLE only:
**Ajouter pour différencier la personne dans les résultats de recherche.**

### 3. When I make a change in an edit page for person/org, I am not warned when I leave that page that my changes won't be saved.
Steps:
1. go into a person/organization (click Edit)
2. Remove the name (en) or remove the image (examples).
3. Exit the page by clicking a left nav option to go somewhere else (like Events)
4. No warning appears telling you that your changes will be lost, and you leave the page. Reenter the org/person edit page to confirm that nothing was changed.

### 4. PASSED my tests
1. Creating a new person/organization in French and English UIs : PASSED
2. Adding an organization that exists in Artsdata but not in Footlight: PASSED with a Caveat
I successfully added and saved the NAC (http://kg.artsdata.ca/resource/K14-29) to Tout Culture Organizations The disambiguating description didn't come through even though it is in the artsdata resource. @saumier, if you have time, can you look at this case?
3. Adding a person that exists in Artsdata but not in Footlight: PASSED

**Comment by troughc** [comment] 2023-09-25 21:24
Guest user login test: 
1.role restriction failed for People and Organizations: When I log in as a guest, i am able to see the "member of an organization' field - this is an Admin only field right? I see this field when I am creating a new place or organization.
2. In the New Organization screen (with the search bar): I search for an organization and find that it already exists in Footlight. I click it and expect to see either the read only page (if I am NOT the creator of this organization) or the same page with an Edit button (if I am the creator or an Admiin). Instead I see this error page:
![Image](https://github.com/culturecreates/footlight-app/assets/64489312/e96b9e21-f3bb-48f7-9e45-a84376eb052c)
3. The same issue as above also happens with People. 

NOTE: for 2 and 3 above, this does NOT happend if I am logged in as an Admin. If I am an Admin, when I click the organization or person in the dropdown that is already in Footlight CMS, I am immediately taken to the edit page.

**Comment by AbhishekPAnil** [comment] 2023-09-26 08:41
2. Retested and not fixed
I search for a name (like Gregory Finch) and I find in in Artsdata. When I click the 'Artsdata' link in the dropdown search I go to a bad page. I go here: https://api.artsdata.ca/K1-3 instead of going here: http://kg.artsdata.ca/resource/K1-3.

3. When I make a change in an edit page for person/org, I am not warned when I leave that page that my changes won't be saved.


@troughc The above issues are fixed and updated  in staging .Regarding the artsdata link:I actually had fixed the issue yesterday for orgs,places but forgot to add same fix for person search.

**Comment by AbhishekPAnil** [comment] 2023-09-26 09:03
@sahalali 
**Role restriction DID NOT PASS for People and Organizations: When I log in as a guest, i am able to see the "member of an organization' field - this is an Admin only field right? I see this field when I am creating a new place or organization. Please recheck permissions.**

Regarding admin only fields in dynamic fields : Could you please add a "isAdminOnlyField" to the taxonomy response.

**Comment by AbhishekPAnil** [comment] 2023-09-26 09:18
@dev-aravind Could you add create by user's id to the response of this https://staging.api.cms.footlight.io/entities  api.I may need it to check for user access while routing to edit pages.

**Comment by dev-aravind** [comment] 2023-09-26 10:36
@AbhishekPAnil Done. It's updated in staging right now.

**Comment by AbhishekPAnil** [comment] 2023-09-28 07:19
@sahalali Please assign this issue back to me when the backend changes are complete.

**Comment by sahalali** [comment] 2023-09-28 10:37
Opened a backend issue to address the backend changes: https://github.com/culturecreates/footlight-calendar-api/issues/666

**Comment by AbhishekPAnil** [comment] 2023-09-29 08:27
@troughc 
_Role restriction DID NOT PASS for People and Organizations: When I log in as a guest, i am able to see the "member of an organization' field - this is an Admin only field right? I see this field when I am creating a new place or organization. Please recheck permissions._

This issue is now fixed in staging

**Comment by troughc** [comment] 2023-10-02 20:51
Tested staging in Chrome
See comment about searching and linking to Artsdata in https://github.com/culturecreates/footlight-app/issues/607

Warning to save work: 
- When I click the left navigation, I get the warning. PASSED
**- When I click "Back to previous page" from the top of Edit Organization / Edit Person / Edit Place page, I don't get a warning to save my work.  NOT WORKING AS EXPECTED**

Role restriction for guest: PASSED


Question/ISSUE: As a test, I changed the name of this person: http://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/people/add-person?id=6511f086925c3900640b761e
I appended "test" to their name "Coeur de Pirate". I noticed that the next time I looked at this person in the CMS, the blue text (for Artsdata entity) displays the name with Test, as being the name in Artsdata - but it isn't. 
screenshot:

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/105b944e-18bb-4fb4-add1-3f15f576839a)

link to artsdata entity: http://kg.artsdata.ca/resource/K12-1002

(I changed the name back in CMS just in case it gets loaded to artsdata).

Why is the blue text showing the name from the CMS instead of from Artsdata? @saumier is it because this Artsdata entity was created from CMS?



Successfully saving/updating an organization then displays to the organization list (not people): PASSED

Not fixed, but can be addressed later. 
Typo in PEOPLE and ORGANIZATION Edit pages: In both PEOPLE and ORGANIZATION is a typo in the English UI - a period (.) is missing at the end of the following sentence:
Add to differentiate organization in search results.
Note that the period (.) is also missing from the equivalent sentence in the FRENCH page for PEOPLE only:
Ajouter pour différencier la personne dans les résultats de recherche.

**Comment by troughc** [comment] 2023-10-02 20:53
@saumier I think we could move this issue to DONE and open new issues for the above if you agree. Please take a look and decide if anything must be fixed before the merge. (the only issue that might be a showstopper the fact that I am not warned that my work won't be saved when I click the breadcrumb, but I don't think so - as long as we fix it in short order)

**Comment by troughc** [comment] 2023-10-03 13:41
At @AbhishekPAnil request, he is going to look at small issues above before we close. Thanks Abhishek.

**Comment by troughc** [comment] 2023-10-03 18:35
@AbhishekPAnil I just noticed something new in People: The occupation field has an empty entry for all People:


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/6faf16a9-b6d4-441f-b548-4228bdc0204c)



It is there, event when I create a new person (in the field - the little circle with the x in it)

An example: http://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/people/add-person?id=642d93bacf606a0064e5fc42

**Comment by AbhishekPAnil** [comment] 2023-10-04 06:49
> @AbhishekPAnil I just noticed something new in People: The occupation field has an empty entry for all People:

The issue is fixed and updated in staging.

**Comment by AbhishekPAnil** [comment] 2023-10-04 08:13
> Why is the blue text showing the name from the CMS instead of from Artsdata? @saumier is it because this Artsdata entity was created from CMS?

This is fixed and updated in staging  for both edit and read only screens.



> Typo in PEOPLE and ORGANIZATION Edit pages: In both PEOPLE and ORGANIZATION is a typo in the English UI - a period (.) is missing at the end of the following sentence:

This is also fixed and updated in staging.

**Comment by AbhishekPAnil** [comment] 2023-10-04 13:44
> - When I click "Back to previous page" from the top of Edit Organization / Edit Person / Edit Place page, I don't get a warning to save my work. NOT WORKING AS EXPECTED

Move  this to a separate issue : https://github.com/culturecreates/footlight-app/issues/646

**Comment by troughc** [comment] 2023-10-04 23:09
Tested name change in Footlight not in blue Artsdata link: PASSED
Typo in PEOPLE and ORGANIZATION in the English UI - a period (.): PASSED
occupation field has an empty entry for all People: PASSED

Yay! Thanks @AbhishekPAnil I will move this to DONE !
Just to note, There is an issue with the occupation taxonomy not mapping to the occupation field. I will log that in a separate issue. 
See you next week!

**Closed** 2023-11-01 01:56 UTC
Labels: feature
