### ISSUE TITLE
Setup Place Types for Tout Culture

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#267] opened 2023-04-04 21:04 UTC
Setup Place type taxonomy so it lines up with LDF model in Wikidata.

https://m.wikidata.org/wiki/File:Core_classes_for_performing_arts_places_in_Wikidata.png

**Comment by saumier** [comment] 2023-04-04 21:07
@troughc Please review the Place Type Taxonomy in our PRODUCTION environment. Thx.
http://oldcms.footlight.io/admin/add-taxonomy/?id=63b85f6c1c6b6c005aad4600

**Comment by troughc** [comment] 2023-04-05 20:38
@saumier I am having trouble reviewing the taxonomy in English due to the same issue Maude encountered in our last meeting (I am getting dashes instead of words - see screenshot). 

I think the taxonomy is okay, but it threw Isabelle and me off to have all the numbers (Q numbers) included. Was this deliberate?



Steps to reproduce:

1. Open the Place type taxonomy to review it. French in displayed. The french displays okay. 
2. Switch to English. I see dashes instead of words. 
3. Switch back to french. I see dashes now instead of words.
4. This is the same whether I am using the French UI or the English UI.
5. View each taxonomy voculary (concept) individually (using the Edit button). This ONLY works if there are words displayed. If you click Cancel in this module, it erases the words (vocabulary) but doesn't close the module. When you click the x to close it, the vocabulary is still in the list.

This happened earlier in my meeting with Isabelle and again now so it seems to be a really bug. And there is the second issue in the edit module.

Screenshot of English:


![Image](https://user-images.githubusercontent.com/64489312/230205187-08d271ea-c616-4de1-8ac2-4907ceceb30a.png)

**Comment by saumier** [comment] 2023-04-07 19:49
I added the Q numbers in the label to help. Those top level types in Wikidata is roughly what Fred concluded with LDI and Dessa has been using those classes when editing Places in Wikidata.  You can decide if it helps or not, and remove them if you want. It is just a label and has no other use than to inform humans what they are selecting (like when we display the Artsdata ID).

**Comment by saumier** [comment] 2023-04-07 19:50
@troughc I also had the --- bug, but it went away.  I think there were some missing bilingual labels. I propose we continue to use it and see if this happens again now that the taxonomies are pretty stable.

**Comment by troughc** [comment] 2023-04-10 19:41
> @troughc I also had the --- bug, but it went away after I dragged a concept to different location and saved the taxonomy. I did not have to clear my cache to make it go away. I think there may have been some missing bilingual labels. I propose we continue to use it and see if this happens again now that the taxonomies are pretty stable. I created a separate issue for this incase we need to prioritize it for launch. 
@saumier No problem, sounds good. Just to note, I still have the bug when I look at Place types (every time).  I will close this issue and we can prioritize the other one.

**Closed by troughc** 2023-04-10 19:41 UTC
