### ISSUE TITLE
Phase 2: Calendar widget and widget settings

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#108] opened 2023-01-10 21:21 UTC
Enable Admins to set up calendar widgets for other websites and provide the embed code.
What is required for this widget:
- Display for the public facing website
- UI for the Admin to set up the widget and provide the necessary code for the destination website

Link to calendar widget and widget settings in the FIGMA (ready for Dev): https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=4213-98576&mode=dev

[analysis document](https://docs.google.com/document/d/1I7sKHZEYNgOd2FJgDhTXysqNmA4K2f3fUHL9OZDfWlI/edit?usp=sharing)

**Comment by saumier** [comment] 2023-04-07 20:07
@troughc Can you please check when the Calendar widget will be needed by Maude, and if she is already using the calendar widget somewhere on a partner website?

**Comment by troughc** [comment] 2023-04-12 21:54
> @troughc Can you please check when the Calendar widget will be needed by Maude, and if she is already using the calendar widget somewhere on a partner website?

@saumier Maude does not have any partner who will use the calendar widget yet. Her plan is to promote it after launch. Also, she plans to train contributors in June.

**Comment by saumier** [comment] 2023-05-03 17:41
Setup Tout Culture's Calendar widget configured to region (Collines-de-l’Outaouais) see email March 17th "RE: checking in on schedule"

**Comment by saumier** [comment] 2023-06-23 22:42
@troughc What is the latest word on the street for giving this to another client?  Is there a design for the first version of this widget (not the screen in CMS to configure, but the actual design)?  I think you made a Figma with Stephanie, but a link to the right place would be appreciated. It is very similar to the Search widget, so my current plan is to assign Abhishek in September. If needed sooner please raise it and we will figure something out.

**Comment by troughc** [comment] 2023-06-27 19:10
@saumier the design we created a couple months ago is in Sprint 14 Figma board. https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates?type=design&node-id=3869-88611&mode=dev
 It is next to the MINIMAL design. It doesn't take into account the design suggestions we recently got from MINIMAL. 
 
 As for any requests from clients, the status is the same. I can check with Isabelle

**Comment by saumier** [comment] 2023-07-24 23:23
@troughc I'll assign this back to you. When you want a work estimate please assign it back to me and I will work with Suhail and Abhishek.

**Comment by troughc** [comment] 2023-07-28 19:08
Latest update: Isabelle needs the widget for her partner before September 21, 2023 (that is her delivery date). I showed her potential filters and design; she liked the idea of being able to set the colours and she asked for the ability to search using different parameters (like by organization, place, title, etc). I said it should work the same way as our search in the CMS
Please confirm @saumier that you can search for title, event type, place (location), audience type or keyword.
Isabelle would also like to be able to create widgets **based on municipality**. Her user story is:
- an MRC like MRC de Collin de Outaouais would like a widget for the region
- a municipality within a region would like a widget for their town; for example Wakefield would like to have a widget that includes all the events happening in Wakefield only.
Currently we don't have the ability to filter by municipality. Let's discuss what we could do.

**Comment by saumier** [comment] 2023-07-30 04:34
@troughc Yes, using our current [CMS Open API](https://api.footlight.io/api/#/Calendar%20APIs/CalendarController_getEventsByCalendarId), we can filter events using Query (query string to match with name, keywords, place name, audience name or type. Also perform advance search using qualifiers is:featured or is:vedette that will return featured events), List of type ids, List of region ids, List of audience ids, List of place ids.

**Comment by troughc** [comment] 2023-07-31 15:56
@saumier what would it take to add municipality to the filters?  
If we were to make country/province/municipalities entities instead of strings (like they are in Wikidata), would we then be able to filter by city name? How much work would that be?

**Comment by saumier** [comment] 2023-08-01 12:27
@troughc This raises many questions and needs a deeper analysis.

**Comment by troughc** [comment] 2023-11-08 19:56
Link to calendar widget and settings in the FIGMA (ready for Dev): https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=4213-98576&mode=dev
cc @saumier

**Comment by saumier** [comment] 2023-11-29 15:01
@troughc FYI - this issue will be analyzed and estimated. Questions may come back and possible changes to the Figma.

@AbhishekPAnil Please analyze the parameters that will be passed to the widget. You can use the readme here as a starting point https://github.com/culturecreates/minimal-footlight-search-widget

Please pay special attention to data-search-events-url and data-event-url, since we do not control the customers website, and this may need to have a url template.  Specifically check how this could work with the signelaval.com website that uses UUID/slug to reach an event webpage, and has a custom search events URL format.
 
** Parameters from Minimal wiget

data-api is the api domain to call.
data-calendar is the id of your calendar.
data-locale is the language of "fr" or "en".
data-event-url is the url on your website for event details. The UUID of the event is added to the end of this URL.
data-search-events-url is the url to display event seach results. The search query is added to the end of this URL.
data-search-events-filter is the name value pair(s) for filtering ALL events. Example: "&region=1234&concept=4567&price-type=free"

**Comment by saumier** [comment] 2023-11-30 13:26
@AbhishekPAnil @SyamBabu-M Please include in your analysis how the data-search-events-url and data-event-url would look like for Signé Laval.

**Comment by saumier** [comment] 2023-12-05 13:43
@AbhishekPAnil @SyamBabu-M Please take some time to research other widgets and learn about best practises are being used for integrating widgets.  For example, bands in town has a widget that may be a good example.

**Comment by saumier** [comment] 2023-12-06 13:54
@SyamBabu-M Please add links that you found here, and your thoughts on pros and cons. Also, please try to setup a test page with the iframe passing the parameters.

**Comment by saumier** [comment] 2023-12-07 14:08
@SyamBabu-M @AbhishekPAnil Please create a document with the proposed parameters so I can review them to complete the analysis.

**Comment by SyamBabu-M** [comment] 2023-12-08 12:55
@saumier I have created the document. Please refer this [document](https://docs.google.com/document/d/1I7sKHZEYNgOd2FJgDhTXysqNmA4K2f3fUHL9OZDfWlI/edit?usp=sharing)

**Comment by saumier** [comment] 2023-12-12 23:43
@SyamBabu-M Please add your estimate in the comment and also add it to the "estimate" property of this issue (top right side).  Then change the label from "estimate needed" to "to be scheduled' and assign to Caitlin. Thx.

**Comment by SyamBabu-M** [comment] 2023-12-13 12:03
@saumier @AbhishekPAnil @troughc https://www.npmjs.com/package/theme-colors I propose to use this package for theme generation. Please take a look.

Please find the estimate for this issue [here](https://docs.google.com/spreadsheets/d/1wtr_fZPDzfZR1AqO230_qWmebb9VfiHAxU7ZtSfNnnE/edit#gid=0)

**Comment by saumier** [comment] 2023-12-13 13:35
Note: Filters in widget (audience and event type) was moved out of scope as per discussion with @troughc on Dec 12, 2023.

**Comment by troughc** [comment] 2023-12-13 14:29
> @saumier @AbhishekPAnil @troughc I propose to use this package for theme generation. Please take a look.

@SyamBabu-M @saumier @AbhishekPAnil  Stephanie and I approve this package.

**Comment by troughc** [comment] 2023-12-14 20:13
@SyamBabu-M I am now assigning this back to you. The figmas for the calendar widget should be stable. The figma for the calendar settings has one outstanding question so perhaps start with the calendar widget settings and front end design. Hope this works for you!
Also, I set the date for December but I recognize that this feature may (will likely) not be finalized before January. But let's get started on it. Thanks!

**Comment by saumier** [comment] 2023-12-18 01:35
@SyamBabu-M please place the code for the widget in the Footlight-CMS repo. I would also like you to think about the use case where many widgets are being used (imagine a website like tout-culture with 30+ widgets) and there is a change to the event url or search url. How can this be managed without needing to change each individual widget?

**Comment by SyamBabu-M** [comment] 2024-01-03 13:08
@saumier @troughc @AbhishekPAnil I forgot to take the ci/cd implementation into consideration when estimating the widget. Due to this, the estimate will be extended by a day. I apologize for the inconvenience.

**Comment by saumier** [comment] 2024-01-03 23:06
@SyamBabu-M Please give me access to comment in your deployment doc.

@SyamBabu-M @AbhishekPAnil @SuhailAliyar I took at look at the deployment document and I think we need to do further analysis. I initially requested that the widget code be placed with the Footlight-CMS code because they are tightly coupled and should be released together (CMS settings for the widget and the widget itself should be in sync).  But I wasn't thinking of 2 sub-directories. I was thinking more along the lines of components with 2 starting points. Like a multi-page app.  Maybe using the Router or another technique.  I did a quick search and found another idea here https://medium.com/@steve.2.farrington/how-to-extend-create-react-app-for-multi-page-applications-4f9c0fb0710c. But when I read this, the need to eject seemed risky. I also found this https://blog.logrocket.com/creating-multiple-entry-points-create-react-app-without-ejecting/

So I see some possibilities:
1. Multi-page app using router in single repo
2. Multi-page app by extending start script in single repo
3. Single-page apps with separate directories in single repo (current proposal by Syam)
4. Single-page apps with separate repos.

Please consider different approaches above (and others that you think of), and write a table of pros and cons taking into consideration the long term maintenance, ease of understanding for a new developer, best practices, ability to keep the widget slim (only include what is needed) and finally the ease of deploying changes to the widget/CMS settings screen together.

Let's discuss when you are ready.  This will take extra days but it is very important and I want to "hurry slowly" so that we build the foundation that works the best for us.

Last note: Since we are using an iframe for the scope of this feature, I propose we drop the build:widget script since the only reason I added that for Minimal was to merge the css and javascript, but this is not needed with the iframe approach.

**Comment by troughc** [comment] 2024-01-12 18:52
@SyamBabu-M fyi, the translations for the calendar widget setup (in calendar settings are available in the CMS copy document) - so you can add that section to the calendar settings page as per @saumier guidance in December (to include configuration settings for the calendar widget in the UI). Thank you!
cc @saumier

**Comment by saumier** [comment] 2024-01-17 13:21
Here is the link shared by Syam in the standup meeting today: https://s3.ca-central-1.amazonaws.com/staging.cms-widget.footlight.io/test-widget.html

**Comment by troughc** [comment] 2024-01-17 14:05
@SyamBabu-M we set up a test page on the culture creates webstie that is password protected. There are a couple issues (Gregory will add a comment on some of this after this comment).
You will be able to see some of the other issues by looking at this page;
TEST PAGE:
https://culturecreates.com/cms-widget-demo/
PASSWORD to view:
pw WidgetTest

**Comment by SyamBabu-M** [comment] 2024-01-23 12:43
@saumier I have made the change to include complete html.

**Comment by SyamBabu-M** [comment] 2024-01-25 04:35
@troughc As disucussed yesterday, I will add the text "Preview desktop version" on to the preview button and on the preview on the side we can show the mobile version of widget. The desktop version can be shown as a modal.

**Comment by troughc** [comment] 2024-01-26 16:31
@SyamBabu-M @AbhishekPAnil, regarding access to this feature: I conducted a poll of our customers regarding which users should have access to the calendar widget settings. Their feedback is for access to be restricted for a variety of business reasons. 
Given this, for this first release to production I would like you to **restrict access to the Calendar widget settings in the UI to ADMINs only**. 
I understand that this will likely require a bit more time to implement this and may require work in the backend. Let me know if you have any blocks.
Thank you. 
cc @SuhailAliyar

**Comment by troughc** [comment] 2024-01-29 17:45
@SyamBabu-M **please read the comment above about role access.** 

Also, I have udpated the figma design to include a title and text for the button. when the browser view is more narrow, the displayed preview and title go away and the user only has the button to preview. The button label changes, and it can go next to the "Appearance" title or just below as discussed (in the same way buttons are displayed in mobile view in all cases)

You can find the correct french and english text in the footlight cms copy document (I tagged you). thanks!

**Comment by SyamBabu-M** [comment] 2024-01-30 18:56
@troughc  this issue can be tested [here](https://pr-929.dla06mbe0wyl7.amplifyapp.com/)

**Comment by troughc** [comment] 2024-01-31 01:59
@SyamBabu-M I really like the way it looks! And it feels easy to use. 
Whilst testing i found a few things.
1. When I am in the Signe Laval calendar, I am seeing the widget for Tout Culture (the widget is pointing to the wrong site - see first screenshot). 
Maybe this is because we don't have the correct URL templates for Signe Laval yet? If so, you can ignore this feedback and just update the URLs so each calendar widget is connected at the right events/search pages for that calendar.

2. in the screenshot below the search results are a bit strange: 
the event in the list "La corriveau - la soif des corbeaux, 27 JAN 2024 to 26 JAN 2024, place855 Bd de la Gappe" is showing the dates in the wrong order (jan 27 - jan 26).
Also, a question because I don't remember: when a visitor filters to a single date, did we decide to only show events that happen on that date? Or should we be showing events on and from that date going forward in time?

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/5c8d0b1c-c88b-4dd9-a3e8-334e4afe6baa)

3.  please hide the filters icon as we haven't added that feature yet. It appears in the search bars of the previews (2 or 3 places)

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/7167e794-ca01-4f19-87b5-f50181c8794b)

4. Please check the figma for guidance on this: When you limit a search by 
 - Date only (example you select January 10): the text at the top of the list of events should say (for example) "3 events -  10 JAN 2024"  Right now the textis "Upcoming 3 events"  
 - Search term display looks good, except add the date if you have a date or date range selected (see figma for examples)

5. I searched Caitlin and then I selected the date these events were happening. Instead of seeing the two events, I got a no results message. See two screenshots below.


Caitlin search term in search bar gives me two results on jan 31 - no date is used to filter results:



![Image](https://github.com/culturecreates/footlight-app/assets/64489312/57adacfe-a96b-47b3-bca9-8731d1ff33f0)



 I then used the calendar to select Jan 31 to filter results of my 'caitlin' search and this was the result:


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/29be7c6f-26db-4713-9794-84ab8e0dbb67)

I will assign this back to you and can keep testing tomorrow. Have a good day.

**Comment by SyamBabu-M** [comment] 2024-01-31 12:23
@troughc 
1: This can only be implemented after the URL templates are added. 
2: I have looked into this. This is caused due to time-zone issues while formatting dates. I am trying to find a fix this without using additional packages. Currently, if only a single date is selected we are sending both start date and end date as that date. So all events that are happening that day will be displayed.
3,4: I have removed the icon and updated the text.
5: I was not able to reproduce this bug. Search "caitlin" returned no results for me in both cases. We can discuss this further in meeting.

**Comment by troughc** [comment] 2024-02-02 19:59
@SyamBabu-M I reteseted everything above and looks good
Found one new issue: some of the single date events are displayed as date ranges. 
### This screenshot shows two events (1st and 3rd in list) happening on Jan 26 but one looks like a date range. Both should be single dates, not date ranges? 
<img width="437" alt="Screenshot 2024-02-02 at 2 37 46 PM" src="https://github.com/culturecreates/footlight-app/assets/64489312/6ee27353-d164-4f4a-9ae6-30f0aedcb250">

Links to the events on TC site - both are single date events with a time:

This one is right: [Brian tyler](https://toutculture.ca/en/event/brian-tyler-and-the-bluestorm-6495c44195ffd60064aabb35/)

- [event in cms](https://pr-929.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/events/add-event/6495c44195ffd60064aabb35)

This one is wrong: [Dumas](https://toutculture.ca/en/event/dumas-645b93ef7db98f0065dc618a/)

- [event in cms](https://pr-929.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/events/add-event/645b93ef7db98f0065dc618a)

### This screenshot shows an event - 3rd in list - that is happening on one date but looks a date range.
<img width="579" alt="Screenshot 2024-02-02 at 2 54 35 PM" src="https://github.com/culturecreates/footlight-app/assets/64489312/7548e90a-ae82-4291-bbcb-ff0f7832daaa">

[Link to event on TC site ](https://toutculture.ca/en/event/alice-de-lautre-cote-64f7524d7d6aa80064353093/)
- [event in cms](https://pr-929.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/events/add-event/64f7524d7d6aa80064353093)

**Comment by troughc** [comment] 2024-02-06 16:46
@SyamBabu-M 

### Findings: 
Links are working: PASSED
Filters: PASSED
Colours: PASSED with caveat. 
**Can the colour picker include these options at the bottom?**


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/7d7f7eab-a382-49c9-9248-67778a63eeca)


### Display on webpage has some issues please see this page for results of testing:
https://culturecreates.com/cms-widget-demo/
PASSWORD to view:
WidgetTest
**Notes:**
when the height is longer to accommodate more events, it looks good in the calendar widget settings page in the CMS; however, it doesn't always display correctly in the test page. I added pertinent details of my settings above each test widget on the test page.
- Note that 2000 height creates a big gap between the search bar and the calendar button (when the page is narrower or it is 2 column display) and there is still a scroll bar even though there is plenty of room to display all (17) events for tout culture or 12 events for Signe Laval.
- the big gap is always there in 2000 height.
- 1000 height seems okay so I don't know where the threshold is.

- clicking See all events button doesn't seem to work consistently. I'm not sure why I dont' get the filtered results everytime? Dates filters it, but not the filters I added? We can discuss if you need
- LOCATION: why is the address showing in the list instead of the name of the venue/location?

**Comment by troughc** [comment] 2024-02-06 20:31
One other thing: the colour sometimes reverts to a previous colour when i change it, in the desktop preview.
Steps to reproduce.
1. choose a colour like yellow
2. change the colour to blue
3. open the desktop preview and do a couple things.
4. sometimes the colour reverst to yellow. (it's a bit inconsistent)

**Comment by troughc** [comment] 2024-02-07 15:06
@SyamBabu-M as discussed at our meeting: 
- Ready for you: I entered text for notifications in the CMS copy docmument and tagged you.
- You can disregard: I cannot reproduce the issue in the previous comment so we will just keep an eye out for it
- Fixed: the height issue seems to be fixed now as per our testing together (thanks!)
- the colour picker can stay as is unless you find a super fast and easy solution (we can do it as an enhancement later)
- please update the location from address to name of place
- I think that's it, but if I missed something please add it here. Thanks!!

**Comment by troughc** [comment] 2024-02-09 17:39
Tested:
names of locations instead of addressed: FIXED
notifications appearing below the field: PASSED (looks good in french and english)

new issues related to the popup warning that appears: 

1. A popup that appears when fields are missing and you try to do an action doesn't display the right info in English and French. In my tests, it always warns the user about adding the colour. This popup appears no matter which field is empty. And sometimes it appears multiple times. 
2. The popup has a red x that you cannot click. IN FRECH: here is another x that is obscured and faint so you can't really see in the french version (on the right). The right x is the one you have to click to close the popup immediately. 
 
**Expected behavior to FIX before releasing the calendar widget:** Make sure the correct message is displayed; make sure the x you use to close (on the right) is always visible and in a circle, designed like this popup: 

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/747093b1-0d06-4bbb-9d56-d896a4529ce1)

**steps to reproduce:**
try leaving some required fields blank and click preview desktop (in french) - multiple popups appear about the colour field
try leaving one field blank and repeat. Usually you see the warning about setting your colour.

### screenshot examples of problematic popups
Message is always the same
**Design should be consistent: the text should be the same and the x on the right should be the same as previous screenshot (within a circle)**
![Image](https://github.com/culturecreates/footlight-app/assets/64489312/e4fddcc0-81cd-490b-a278-9fdfe18cdc1d)

**x is obscured in french**

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/bea107f9-fa34-4844-a35b-59c8fcc97183)

Note: I may revisit the popup warning design to match the [Figma](https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=22%3A432&mode=design&t=MS8HDwyieAVnX0Ex-1) in a separate issue, but this is not the priority for now.

**Comment by troughc** [comment] 2024-02-12 16:56
Tested: PASSED! :)
cc @SyamBabu-M @sahalali

**Closed** 2024-02-14 06:26 UTC
Labels: feature, To be deployed
