### ISSUE TITLE
Event series update: when to delink from Artsdata

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1154] opened 2024-06-10 22:04 UTC
In an event with multiple dates (event series), when the dates are modified in the CMS by a user in any way, the event series in the CMS should be delinked from Artsdata (it is no longer valid) after saving. Examples of date changes:
- date-time is removed from a published and linked event series
- date-time is added to a published and linked event series
- date-time is changed in a published and linked event series (for example the time is changed)

Expected behavior: 
User opens a published and linked event series and modifies the dates in some way. User saves.
- The event series is delinked from Artsdata. 
- In the CMS UI, the link icon is removed from the list view. The link is removed from the event details view (so it is not there the next time the user opens the event).

cc @saumier 

Test event : Example event: https://staging.api.footlight.io/events/666144a5beddbb0064698f83

Test Cases :

1. Find the event series in [Crow's calendar](https://staging.cms.footlight.io/dashboard/6628c7600796c300645636b0/events?page=1&order=asc&sortBy=upcomingEventDate) .Change the custom dates and check if the dates are persisted properly and artsdata link is removed.
2. The artsdata link should only be removed for events which are published.
3.Change the event series to daily,weekly,single date and date range and check if the artsdata link is removed.

Remember to bypass the privacy window by going to the swagger link : https://15.222.238.246/api/

**Comment by SyamBabu-M** [comment] 2024-06-19 11:12
@dev-aravind This requires backend changes. Please look into this. Thanks.

**Comment by dev-aravind** [comment] 2024-06-21 13:08
@AbhishekPAnil This issue should be handled by the frontend as there is no way of knowing whether if an event was updated by the CMS or the Aggregator. (We don't need to delink the issue if the update was done by the aggregator.)

**Comment by troughc** [comment] 2024-06-27 17:08
Tested in signe laval

Expected behavior:
User opens a published and linked event series and modifies the dates in some way. User saves
- TESTED on[ this event](https://pr-1185.dla06mbe0wyl7.amplifyapp.com/dashboard/63457978637093005071a053/events/add-event/665832c78c76ef0064569aff) which had 8 occurrences - I extended the weekly recurring series by one week, making it 9 occurrences.

The event series is delinked from Artsdata.
- In the CMS UI, the link icon is removed from the list view: DID NOT HAPPEN



![Image](https://github.com/culturecreates/footlight-app/assets/64489312/ad43f9df-6f4e-466b-9386-cc84279df751)


- The link is removed from the event details view (so it is not there the next time the user opens the event): DID NOT HAPPEN




![Image](https://github.com/culturecreates/footlight-app/assets/64489312/6d2362bf-89f1-4af1-a51c-02ee5a81d3f0)

**Comment by troughc** [comment] 2024-07-29 15:01
I modified this event but it is still linked to Artsdata: https://pr-1243.dla06mbe0wyl7.amplifyapp.com/dashboard/63457978637093005071a053/events/66a7acd7a4c15e00a2a84b31

**Comment by AbhishekPAnil** [comment] 2024-07-29 16:40
@troughc Did you open the pop up for editing the events or just added the weekdays ?

**Comment by AbhishekPAnil** [comment] 2024-07-29 17:37
@troughc Did your testing work when changing an event series date to daily,date range ?Was the artsdata link removed during these changes?

**Comment by troughc** [comment] 2024-07-29 18:53
> @troughc Did you open the pop up for editing the event dates or just added the weekdays ?

I did NOT open the popup (custom dialog). I just edited the days and times in the main CMS window.

**Comment by troughc** [comment] 2024-07-29 19:00
> @troughc Did your testing work when changing an event series date to daily,date range ?Was the artsdata link removed during these changes?

@AbhishekPAnil I just tested this one - changed from weekly to date range: https://pr-1243.dla06mbe0wyl7.amplifyapp.com/dashboard/63457978637093005071a053/events/6669113c92cafd0064973fe9

It did not remove the Artsdata link - the Artsdata link is still there.

**Comment by saumier** [comment] 2024-08-19 19:10
@AbhishekPAnil I am having trouble accessing https://pr-1243.dla06mbe0wyl7.amplifyapp.com and I think this may have already been merged into the main branch. I think we should close this as I am not sure what I am testing. I have a series of Use cases that I will use moving forward and can open a new issue if needed.

**Comment by saumier** [comment] 2024-08-20 21:42
@AbhishekPAnil My first test did not pass (unlucky).

I edited this event Laurent Paquin https://pr-1243.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/events/64af64803c19fa0064e77639

After I changed the sub-events, the event series was still linked to Artsdata.

**Comment by saumier** [comment] 2024-08-28 03:14
@AbhishekPAnil I have having trouble testing. When I click to edit an event, and then click publish without making any changes, the event disappears.  Can you reproduce this as well?

**Comment by AbhishekPAnil** [comment] 2024-08-28 06:10
> [@AbhishekPAnil](https://github.com/AbhishekPAnil) I have having trouble testing. When I click to edit an event, and then click publish without making any changes, the event disappears. Can you reproduce this as well?

Yes , I was able to reproduce the same. The reason i didn't notice this initially was because I used the event's id to come back to edit page every time.

**Comment by sahalali** [comment] 2024-08-30 10:31
@AbhishekPAnil It was a backend-related issue. The issue has been fixed and deployed. Can you please review it? If it looks good, then please assign it for review.

**Comment by saumier** [comment] 2024-09-12 21:55
@AbhishekPAnil This event has 2 occurences, but when I click "edit" button the date range is not shown.  Is this something that needs to be fixed as part of this issue?

![Image](https://github.com/user-attachments/assets/165b05fc-2d99-4d7d-8de1-290af6133fd0)

**Closed** 2024-09-24 11:54 UTC
Labels: bug, To be deployed
