### ISSUE TITLE
Duplicate Places, Person, Organizations in Culture Mauricie

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#971] opened 2024-02-13 15:47 UTC
Editing and saving Places, People and Organizations  are not working properly in production:

(1) I cannot edit to add missing information to Places: DONE
(2) There are duplicate Places with the same name appearing in the Places List. (Example: Musee POP, Amphitheatre Cogeco) -  PENDING

Steps to reproduce issue:
- Try to edit a Place  and save.
- The following error appears.

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/32e6f5a4-0ea0-4a67-ac59-5d66b7780a3b)

**Comment by sahalali** [comment] 2024-02-14 06:34
Point 1 in this issue is a duplicate or the root cause of the issue is the same as of https://github.com/culturecreates/footlight-app/issues/969. Its now fixed by @dev-aravind

**Comment by troughc** [comment] 2024-02-14 17:33
Additional information regarding missing required fields in Places (specifically the address fields). This bug is also present in Tout Culture.
Example is [this place](https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/places/65c5247b7f90c70063659b14)

This place was created by [this GUEST user](https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/settings/user-management/65c51fa97f90c7006365998f)

The only event this user created is in the past [here](https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/65c52a527f90c7006365a695)

And that event was updated by an ADMIN (Scott), who probably fixed the location - the event is linked to a different place ([a complete, correctly entered place at the same address](https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/places/6499f9d03c19fa0064e4e162))

**Comment by sahalali** [comment] 2024-02-15 11:24
@troughc The missing required fields in the Tout Culture calendar are a different issue. [this place](https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/places/65c5247b7f90c70063659b14) is missing address, may be because the user might have missed to enter it.

Point 2: Missing address or required fields from Caligram was a glitch in the aggregator. That issue is not fixed.  

Point 3: Duplicate Places, Person or Organization is a know issue at the moment. Its happening because, a common identifier could nt be identied among the different sources. Inorder to fix this issue, we could develop unique identifiers for different entities. 

Currently entities with same name but from different sources are treated different entities because it doesnot have a uniques identifier.
Proposed solution:
1.  Reconcile entities by Artsdata Ids within Ontorefine and use it as uri for the entity. @saumier Please advice here.
2. Create uri with a common namespace followed by name of the entity. It is not a perfect solution, since a small difference in the name will again treated as a new entity.
3. Manually updating an entity with URIs of duplicated URIs and deleting duplicated entities keeping on entity with other URI. (Time consuming and not maintanable)

**Comment by troughc** [comment] 2024-02-15 13:19
> [@troughc](https://github.com/troughc) The missing required fields in the Tout Culture calendar are a different issue. [this place](https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/places/65c5247b7f90c70063659b14) is missing address, may be because the user might have missed to enter it.

I will log this in another issue.

**Comment by saumier** [comment] 2024-02-16 13:29
@saumier  to document Artsdata reconciliation with OntoRefine to solve the duplicate places problem,

**Comment by saumier** [comment] 2024-02-19 02:47
@sahalali Here are the reconciliation steps to reconcile Places with Artsdata using OntoRefine.

These are manual steps:
1. Create a spreadsheet with Places (from the API data in this case).  I propose using place name and postal code as input to reconcile.
2. Open the spreadsheet in OntoRefine.
3. Click the name column heading and select "reconcile > start reconciling...."
4. In the recon popup - click the orange button "add standard service" in the bottom left --> open "Add service" popup
5. Enter "http://api.artsdata.ca/recon" and click the button "add service"  --> "Add service" popup closes
6. Select the "Artsdata Reconciliation service" on the left of the Recon popup.
7. Check that system automatically selected schema:Place
8. Select the column checkbox "postalCode" and add the property "schema:address/schema:postalCode"
9. Click the button "Start reconciling..."

<img width="951" alt="Screenshot 2024-02-18 at 9 41 36 PM" src="https://github.com/culturecreates/footlight-app/assets/419491/0081c28b-27ed-4a7e-8e0e-1de30066e3b0">

**Comment by saumier** [comment] 2024-03-19 02:14
@sahalali I confirmed that the duplicate places  Musee POP, Amphitheatre Cogeco are fixed. Looks good. I'm not sure what else to check so I will close this issue.

**Closed** 2024-03-19 02:23 UTC
Labels: bug, Mauricie
