### ISSUE TITLE
Pass locationId as undefined when user removes a location from event

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#863] opened 2023-12-13 12:40 UTC
Bug: The user is unable to remove a location linked to an event .

Expected behaviour : The user should be able to remove a place and save the event as DRAFT.
@AbhishekPAnil Please pass locationId as "undefined" in the payload while removing a place linked to an event.

**Comment by sahalali** [comment] 2023-12-13 13:23
This looks like a backend issue. You can assign to me or @dev-aravind when scheduled.

**Comment by troughc** [comment] 2023-12-14 20:23
@sahalali I am assigning this to you then. cc @AbhishekPAnil

**Comment by dev-aravind** [comment] 2023-12-18 12:53
@troughc This is fixed in staging right now.

**Comment by troughc** [comment] 2023-12-18 21:17
Tested staging on Chrome
### I cannot save an event as draft when I remove it's location. 
Steps to reproduce:
1. Open a published event; for example in Tout Culture (TC), open "Ciné Jonction..." (second event in list).
2. Remove the location.
3. Try to use the dropdown to switch from Published to Draft. An error appears saying "This event needs more information before it can be saved". 
Expected behavior - I should be able to change the state from Published to Draft AFTER I remove a location.
Notes: 
- I can change the state from Published to draft if I remove a non-mandatory event detail (example, event link)
- I can change the state from Published to Draft if I don't remove a mandatory property from the event details (examples, location or audience in TC calendar). 
- I cannot change the state in the event details if I remove a mandatory field (examples, location or audience in TC calendar).

**Comment by dev-aravind** [comment] 2023-12-19 05:45
@troughc This seems to be a frontend issue. @AbhishekPAnil  Please look into this.

**Comment by troughc** [comment] 2024-01-15 17:21
Additonal test FYI: 
Removing a location from an existing published event and saving as draft(my test was conducted with this [aggregator event](https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/64af646d3c19fa0064e773a8):
Goal: add a location and publish event in one step. This did not work. Instead, I had to save as draft first.
Steps to reproduce
1. Save the above event as draft.
2. open the event and remove the location. Save as draft.
3. open the event, add a location, then click Publish. This error appears:


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/9fdadbc5-efc2-493a-ad62-f5afcbd56838)


2. Workaround: Instead of clicking publish, save the event with the location (as draft).  Success.
3. Open the evnet and publish (or right-click to publish the event). Success.

**Comment by SyamBabu-M** [comment] 2024-01-30 15:16
@troughc You can use [this](https://pr-930.dla06mbe0wyl7.amplifyapp.com/) link to test this issue.

**Comment by troughc** [comment] 2024-01-30 17:18
@SyamBabu-M I tested this and found a small bug (edge case).
Steps to reproduce the bug:
1. Click on a published event.
2. Remove the location. 
3. Click Save (do not use the dropdown). An error message appears because the REQUIRED location is missing (which is good). Notice that there is no location in this screenshot:

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/abcb22e3-3bb9-4d7a-b0d1-636327d87c15)

4. Now use the dropdown to save as draft. A success message appears and the event is saved as draft (which is good).
5. BUG: however, the event is saved as draft WITH the location I just removed, as shown in this screenshot from the event list (notice the location is shown):

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/fdb68879-3edb-4c9e-9440-559e7e02b897)

6. Reopen the draft event to confirm that the location is there. It is.

Note: If i simply remove the location and then use the dropdown to save as draft, everything works fine. This bug appears when I click Publish and then I use the dropdown to save as draft

Expected behavior: when I remove a property like location and follow the steps above, the location should NOT be added back to the event.
Thanks!

**Comment by SyamBabu-M** [comment] 2024-01-31 12:48
@troughc this is fixed.

**Comment by troughc** [comment] 2024-01-31 17:12
@SyamBabu-M I tried this pull request link from the top of this issue: https://github.com/culturecreates/footlight-app/pull/930

I think it is the same one from yesterday so it didn't show your fix - but i can't find the new pull request? Can you point me to it please?

**Comment by AbhishekPAnil** [comment] 2024-01-31 17:47
> I think it is the same one from yesterday so it didn't show your fix - but i can't find the new pull request? Can you point me to it please?

@troughc The additional changes were done in the same PR.Hence it should be automatically be reflected in the same preview url.
The reason the recent changes didn't show up in the preview url is because somehow the base branch automatically switched from develop to main.Usually the deployment is triggered when we have a PR to the develop branch.I have now changed it back to develop and redeployed the version.Please look check it out and let me know if the recent changes updated in the same preview url.

**Comment by AbhishekPAnil** [comment] 2024-02-02 05:32
Note : Updated in staging

**Closed** 2024-06-21 14:47 UTC
Labels: bug
