### ISSUE TITLE
Cannot open event in Production

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#681] opened 2023-10-13 12:53 UTC
SignéLaval events in Draft loaded by Aggregator cannot be opened to see details in production

https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/6526a773731d520064209734

```
{
    "status": "failed",
    "error": "Cannot read properties of null (reading 'length')",
    "currentTime": "2023-10-13T12:51:57.333Z",
    "path": "GET /events/6526a773731d520064209734"
}
```

**Comment by dev-aravind** [comment] 2023-10-13 15:15
@saumier Fixed the issue. It was caused by the way we handle null organizer data in admin-api when updating an event. I made some minor changes and merged it as a hotfix and also ran aggregator which fixed all the events that had empty organizers in them.

Please review it and let me know if you find any other issues.

**Comment by saumier** [comment] 2023-10-13 16:58
@dev-aravind Great. Thanks so much for fixing this. And thanks for the explanations. I appreciate it :-)

**Closed** 2023-10-13 16:57 UTC
Labels: bug, Signé Laval, Customer blocked
