### ISSUE TITLE
Integrate regression testing into release pipelines

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#931] opened 2024-01-30 14:35 UTC
For reference: https://docs.google.com/document/d/1xw_jwnMMgg93DuPYcA5GPAyvnQ70AoFE9EUeWLBrhvI/edit

@sahalali is working with Kim on this one.

**Comment by sahalali** [comment] 2024-02-13 08:05
@troughc We can wait until Kim Prepares the runnable Regression test script.

**Comment by sahalali** [comment] 2024-03-19 14:23
Waiting for @kmdvs to complete the regression test scripts.

**Comment by troughc** [comment] 2024-03-27 20:02
### Regression test status update: 
- Keeping the versions up-to-date on his testing platform
- Kim is working on updating the scripts now (for general tests to be in sync with latest version)
-  Will work on script for Github to launch Cypress (so that it can be used on Docker and so that it is more flexible in terms of test options) 
- Notes that he needs to stay in sync with the latest version - not sure exactly how to make sure the synchronization occurs (how to track the release schedule so he can release his regression test just after, maybe the next day) 

> - **To be decided**: how to inform Kim IN ADVANCE to update the regression test so that it can be ready ASAP - is there a release schedule he could follow? How to communicate emergency releases? 

cc @kmdvs @sahalali

**Comment by saumier** [comment] 2024-06-12 13:14
@sahalali What is the status on this issue? Is this an old issue that should be closed or still active?

**Comment by sahalali** [comment] 2024-06-13 03:45
@saumier We are waiting for Kim to come back with the final script. Once that is ready, we can integrate the regression tests with our development process.

**Comment by sahalali** [comment] 2024-08-05 05:35
@dev-aravind 
1. Please add a workflow in the footlight-calendar-api repo to manually run the regression test with sufficient input options.
2. Try to create a reusable action for the regression test, so that we should be able to reuse the action to run different regression tests

**Comment by sahalali** [comment] 2024-08-28 13:04
The use case diagram: https://www.figma.com/board/5cKuhr1s0kHWthxh3wZRYZ/Workflow-(Copy)?node-id=0-1&t=asEwBTitca1zIXcF-0

**Comment by dev-aravind** [comment] 2024-08-30 10:31
@AbhishekPAnil Please make the changes that Kim requested and assign this back to me. Thanks

**Comment by dev-aravind** [comment] 2024-09-20 09:17
@AbhishekPAnil There are still some error when testing in the github runner. The tests run fine when pointed to the staging website. Look [here](https://github.com/culturecreates/footlight-app/actions/runs/10954049502) for reference.

**Comment by troughc** [comment] 2024-10-10 19:46
Hi @dev-aravind, I am just meeting with @kmdvs and we decided to deprioritize testing in Chrome. Instead, for now, let's run the test in Firefox only. 
If we need to revisit this, we can add Chrome back in at a later time.
cc @saumier

**Comment by dev-aravind** [comment] 2024-11-11 12:59
@AbhishekPAnil Please merge this [PR](https://github.com/culturecreates/footlight-app/pull/1442) for the tests.

**Comment by dev-aravind** [comment] 2024-11-20 12:56
Assigning this to @kmdvs as he is working to fix the current errors in the regression tests regarding modification of entities.

**Comment by kmdvs** [comment] 2024-11-22 10:02
Fixed as [test 1](https://github.com/kmdvs/cypress-gha-tests/actions/runs/11967651119) and [test 2](https://github.com/culturecreates/footlight-app/actions/runs/11969782328) passed 100%

**Comment by dev-aravind** [comment] 2024-11-26 12:18
@sahalali Please review [this](https://github.com/culturecreates/footlight-app/pull/1464) PR to add the regression test into our CI/CD pipelines. Let me know if you need any changes.

**Comment by kmdvs** [comment] 2024-11-28 21:01
This can be closed now, since [#1464](https://github.com/culturecreates/footlight-app/pull/1464)?

**Closed** 2024-11-29 13:24 UTC
Labels: bug

**Comment by troughc** [comment] 2024-11-29 13:32
https://www.figma.com/board/5cKuhr1s0kHWthxh3wZRYZ/Workflow-(Copy)?node-id=0-1&node-type=canvas&t=gG9LXBwl68jJVfPR-0
