### ISSUE TITLE
Can't publish event in Tout Culture staging

### ISSUE THREAD

**Issue by kmdvs** [culturecreates/footlight-app#1167] opened 2024-06-18 18:33 UTC
The following event seems to have all mandatory fields filled, but can't be published

https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events?page=1&order=asc&sortBy=upcomingEventDate&query=Copie+de+Copie+de+Copie+de+Copie+de+Copie+de+Titre+francais

It gives a general error page like this one, obtained when there's a missing image (this time test was in production)
![2024-06-18 13_51_44-Greenshot](https://github.com/culturecreates/footlight-app/assets/44624797/0f2cb0f3-f450-4c14-9a01-81cc13a88a70)

**Comment by kmdvs** [comment] 2024-06-18 18:49
Changed to https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/6671c14e3d561e00a1dbf511

When trying to publish from the event page, the pop-up will appear. 
Saving as draft and then selecting "Publish" in the drop-down at that point will trigger the error page

**Comment by dev-aravind** [comment] 2024-06-19 07:06
@AbhishekPAnil The issue is now fixed in staging right now, it was caused by the "Event Type" taxonomy being accidentally set as a dynamic field. There is one more issue where the event cannot be published from the listing page. Can you please look into this?

**Comment by troughc** [comment] 2024-06-19 15:48
@kmdvs I tested this and it is working for me now. The test environment is https://pr-1169.dla06mbe0wyl7.amplifyapp.com/ 
Do you want to test it too?

**Comment by kmdvs** [comment] 2024-06-19 18:05
@troughc Yes it seems to work now :) Great

**Comment by troughc** [comment] 2024-06-19 18:59
@kmdvs I reopened and moved this back into in review - It still needs to be deployed. 

And thank you for testing!

**Comment by kmdvs** [comment] 2024-06-19 19:57
Alright, I should've checked the bug cycle before :)

**Closed** 2024-06-20 05:47 UTC
Labels: bug, To be deployed
